#!/bin/sh
# file name: gitdisk-update
# description: gitdisk update script
# create date: 2016-02-18 19:52:12
# author: amoblin
# This file is created by Marboo<http://marboo.io> template file $MARBOO_HOME/.media/starts/default.sh
# 本文件由 Marboo<http://marboo.io> 模板文件 $MARBOO_HOME/.media/starts/default.sh　创建

#name=`basename "$1"`
#name_without_extension=`echo ${name%.*}`

if [ ! -d .git ]; then
   git init
fi
git add -A
git commit -m "update content"
git push
